= musecnav
:toc: top
:toclevels: 3
:experimental:
:icons: font
//:sectlinks:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
//:hide-uri-scheme:
// :source-language: python

ifdef::env-github[]
:toc-placement!:
toc::[]
endif::[]

Vim plugin for **M**ark**U**p **SEC**tion **NAV**igation 

For the time being, though, a more accurate name would be _adsecnav_ for
**A**scii**D**oc **SEC**tion **NAV**igation because I've put all my energy into
making it work for Asciidoc/Asciidoctor. Proper Markdown support will be there
eventually.

== Disclaimer

This plugin is a personal project that I made for my own education and use. A couple
people expressed interest in it so I'm sharing it but with some mild warnings related
to stability of the script, responsiveness to enhancement requests and non-critical
bug reports, and things like that. Caveat emptor.

That being said, what was first and foremost an educational project has turned into a
super useful tool to me that I use all the time so why the heck not put it out there?

== Overview

_If you just want to jump in and go a quick read of <<hot-keys, Hot Keys>> should be
all that you need after installation._

I regularly edit text containing Asciidoc markup and thought it would convenient to
be able to easily jump to any section in such documents. Since I'm a long-time coder 
and Vim fan I thought rather than use something already available I'd make it an
excuse to improve my Vim knowledge. Never written a Vim plugin before.

All this does, essentially, is open a menu when called in which all of the document's
sections are available and which can be navigated as a hierarchy (as opposed to
displaying all of them at once). Choose a section and you will be taken to its
header.

Well, it's a bit more complicated than that. Funny how much nuance there is for
something that sounds so simple on paper. I try to cover most of that below (though
that's a WIP).

Currently this is tested with Asciidoc and, lightly, with Markdown (see
<<known-issues, Known Issues>>). The 'mu' in musecnav is for 'markup' so the
idea is to support whatever formats are needed. There's a bit more information on
supporting additional formats in <<plans, Plans>>.

== Installation

Standard stuff if you use a plugin manager that plays nice with GitHub, e.g.

.vim-plug configuration
----
Plug 'b-layer/musecnav'
----

== Feature Details

Besides the obvious stuff mentioned above I note some less apparent details here.

You can use either a slide-up (from the status line) menu or, with newer versions of
Vim, a popup window. With a compatible version you'll get the popup by default.
Otherwise you'll see the slide-up. To change this see <<settings, Settings>>.

When the menu is displayed its state should always reflect the current section
hierarchy and the current cursor position (see <<reset, Hot Keys - Reset>>). As a
result, it can be used just to 'get your bearings' in a large document.

The sections visible at any particular time in the menu depend on what has been
selected by the user prior. If user hasn't selected anything since start/reset and/or
the cursor is at the beginning of the document you'll see:

   Document root (level 0)
     All level 1 section headers

When a (level 1) section is chosen you'll see:

   Document root (level 0)
     All level 1 section headers
       Selected section's entire subtree

When a section header deeper than level 1 is selected it'll be:

   Document root (level 0)
     Selection ancestors (level 1 to N-1)
       All children of the selection's parent children (level N)
         Selected section's entire subtree (level N+1 on down)

In all cases the full ancestral line from current section to root of the document
should be visible.

=== Hot Keys

By default no keys are mapped. To enable the hotkeys described below add the
following to your vimrc:

    let g:musecnav_use_default_keymap = 1

Otherwise see <<key-mappings, Key Mappings>> for help with defining your
own hotkeys.

kbd:[F7] :: Open the navigation menu (popup or message based depending on config).

==== Popup Menu

kbd:[J]/kbd:[K] or kbd:[Down]/kbd:[Up] :: Select row below/above the currently selected row.
kbd:[Shif+J]/kbd:[Shif+K] :: Select last/first row.
Numbers 1-99 :: Jump to a row by number (see next section).
kbd:[Enter] :: Go to section matching selected row. Menu remains open. If you
hit kbd:[Enter] again immediately (without choosing another row) the menu will close.
kbd:[Esc] / kbd:[Ctrl+C] / kbd:[X] :: Other ways to close the menu (at any time).

==== Slide-up Menu

Numbers 1-99 :: Rows are chosen by entering their associated number followed by Enter.
kbd:[Esc] / kbd:[Ctrl+C] or kbd:[Enter] by itself :: Close the menu.


==== Reset

`musecnav` monitors the current buffer and if it detects a change that could impact
the line numbers of any sections in the saved hierarchy it will rescan the file and
rebuild the hierarchy the next time the menu is opened. Nonetheless, you may
occasionally want or need to use one of these:

kbd:[Shift+F7] :: 'Soft reset'. Rescan section headers and open the navigation
  menu. Cursor position will be preserved.

kbd:[Ctrl+Shift+F7] :: 'Hard reset'. Rescan doc and section headers, reset the
  cursor to the first line of the document and open the navigation menu.

=== Numerical Selection in the Popup

A nice feature is being able to choose sections by entering the associated number.
(By default Vim popups don't support this which means you might have 50 sections on
screen but no way to navigate them except up or down, one line at a time!) That
being said, the way I implemented things _might_ seem a little peculiar. So I spell
out the algorithm here.

There is a 1-digit 'buffer' that is empty when menu is opened.

* User enters a number when buffer is empty...
** ...if number matches a single row, and is not the first digit of any other row numbers select the matching row (buffer remains empty)
** ...if number could match multiple rows, select first of potential matches and
   buffer the number
* User enters a number when buffer is not empty...
** ...if combined number (previous is most significant digit, new is least
   significat) matches a single row, select that row and clear buffer.
** ...if combined number doesn't match a row, discard new number (previous number
   remains in buffer)

Example: 32 rows. User enters 3. Select line 3 and buffer num (in case they intend to
go to 30, 31 or 32). User then enters 5. No
row 35 so discard 5 (leaving 3 in buffer and row 3 selected) User enters 1. Select
row 31 and clear buffer. User enters 9. Select row 9 but don't buffer num (no rows
90-99). User
enters 2. Select row 2 and buffer num. Etc. When user finally accepts selection with
Enter buffer is always cleared.

If you get confused hit Enter and retype desired number. (Though, really, it's not
THAT confusing.;) 

CAUTION: This only works for 2-digit numbers so if you have 100 or more sections
visible in the menu _at one time_ (!) the behavior is undefined. (The most I've seen
at once, and I regularly navigate a 250-section bad boy, is about 80.)

== Settings

=== Key Mappings

As mentioned in the <<hot-keys, Hot Keys>> section you can enable default key
mappings with:

    let g:musecnav_use_default_keymap = 1

If you'd prefer to define your own mappings it works like most plugins out there:
find the applicable `<Plug>` mappings and map the desired key(s) to the ones of
interest. You can find the `<Plug>` mappings for musecnav with this:

    filter /musecnav/ map

The most important one is that which launches the navigation menu/popup.
Specifically, `<Plug>MusecnavNavigate`. Using the default keys as an example a
mapping to that would look like this:

        nmap <F7> <Plug>MusecnavNavigate

The only other `<Plug>` mappings you might want to consider configuring are
`<Plug>MusecnavReset` and `<Plug>MusecnavReinit`. Their functionality is described
here: <<reset, Hot Keys - Reset>>.

=== Popup Menu Colors

If you are using the popup menu, note that Vim popups are colored based on highlight
groups `Popup` and `PopupSelected` or, if those are not set, `PMenu` and `PMenuSel`.
Because popups are relatively new you'll find that `Popup`/`PopupSelected` are rarely
set in color schemes. That means the `PMenu` groups are used and those aren't
explicitly set too often either which means you end up with the default for `PMenu`
which is a garish pink/violet. So I decided to define the two `Popup*` groups by
default. Instead of a fixed set of colors, though, I link them to other highlight
groups. This way they will match (usually) whatever color scheme you are currently
using.

If you still want to override them you are free too. Example:

    hi Popup guifg=#3030ff guibg=black
    hi PopupSelected guifg=black guibg=#a0a0ff

=== Other Settings

Turn off popups and enable the slide up navigation menu with:

    let g:musecnav_use_popup = 0

Change the in-menu 'current section' indicator like so:

    let g:musecnav_place_mark = '*'

== Performance

I regularly use the plugin with an asciidoc file having 250 sections across more than
8000 lines and, almost always, it's super fast and smooth in each of my vim/gvim
versions. (Caveat: I do have a pretty beefy PC.) I say almost always because for
reasons I don't yet understand it occasionally takes 10 or so seconds to scan the
file. Not every time I open a document launch the popup or every time I do a hard
reset (Ctrl-F7) but _some_ of those times. I need to investigate but it's rare so I
don't feel much urgency. I'd be interested in hearing from anyone having a
significantly more negative go of it.

== Known Issues

WARNING: Markdown is currently pretty broken as I've been refining the Asciidoc
support but I do plan on getting Markdown working well eventually.

TIP: Use the primary header formats for Asciidoc and Markdown: single-line, starting
with one or more `=` (Asciidoc) or `#` (Markdown). I may improve handling of the
secondary formats in the future but right now they're just not a priority (I never
use them).

=== Markdown

There is currently rudimentary support for the Markdown format. The common ways of
indicating headers are recognized per the following:

----
  # H1
  ## H2
  ### H3
  #### H4
  ##### H5
  ###### H6
  
  Note: Some implementations allow omitting the space after the '#'s. musecnav
  allows for this.
  
  Alternatively, for H1 and H2, an underline-ish style:
  
  Alt-H1
  ======
  
  Alt-H2
  ------
----

Having run through a relatively large number of open-source Markdown files I've found
that some people have little concern or knowledge of valid section flow (primarily
meaning they will jump down more than one level between adjacent sections). There
also seems to be a correlation between such people and use of the alternative header
format. Besides, "keep your section numbering valid!", my advice (and a growing
consensus, it seems) is to stick to the primary format (e.g. "## H2"). At this point
I'm not putting any energy into robustly handling the alternative.

Beyond that...

There must be a blank line preceding each header. This helps eliminate some issues
such as the one described next but if it turns out to be blocking valid Markdown or
otherwise more trouble than its worth I'll change it.

Some corner cases will trip up _musecnav_. For example, if you have
a code section (ie. delimited by `++```++`) containing Bash and it includes a Bash
comment (e.g. '# this is a comment') in the first column it will be mistakenly
identified as a Markdown header.

=== Asciidoc

Only a single "level-0" section title is recognized (these are identified by a single
`=` at the beginning of the line). While that is all that is allowed in the `article`
and `manpage` doctypes the `book` doctype can have many. These represent a book's
"parts" and they can contain multiple chapters (level 1).

Asciidoc has an include directive and one thing it allows is seamless inclusion of
other Asciidoc files. After conversion the primary file and the included files appear
as a single document. Currently, included files are ignored but at some point I think
it would be cool to allow navigation of them. Their sections would be
integrated in the navigation menu. Upon selection of a section the appropriate file
would be loaded, perhaps in a new window, and focus/cursor shifted to the selected
section header within.

(Regarding preference for Atx-style headers over Setext-style see
http://asciidoctor.org/docs/asciidoc-recommended-practices/ for more info.)

== Plans

As mentioned earlier I may support additional markup formats. It's really easy to add
new formats so it works most of the time. Just match a pattern. That hard(er) part is
sniffing out the exceptions and handling them. For example, Asciidoc allows section
headers independent of the main hierarchy by preceding them with `[discrete]`. Code
had to be added to ignore these.

At a minimum, I want to fix all outstanding Asciidoc issues and those Markdown issues that are likely to be encountered relatively frequently.

Further out, I've thought a bit about the possibility of extending this to work
beyond markup section headers. Examples: functions/methods for this or that
programming language, Vim fold markers, user-defined delimiters, etc. That's getting
quite a bit ahead of ourselves, though.
